# Generated by Django 4.2.5 on 2023-09-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shared', '0005_alter_biguser_table_alter_mechanic_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('icon', models.ImageField(null=True, upload_to='images')),
                ('tags', models.CharField(max_length=150)),
                ('post_published', models.DateTimeField(null=True)),
                ('post_last_updated', models.DateTimeField(null=True)),
                ('stock_capacity', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shared.mechanic')),
            ],
            options={
                'verbose_name': 'Pjese Makine',
                'verbose_name_plural': 'Pjeset e Makines',
                'db_table': 'machine_parts',
            },
        ),
    ]
