# Generated by Django 4.2.5 on 2023-09-19 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachineParts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMachineParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.PositiveIntegerField()),
                ('rating_text', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'machine_parts_rating',
            },
        ),
    ]
