# Generated by Django 4.2.5 on 2023-09-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachineParts', '0002_ratingmachineparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmachineparts',
            name='machine_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MachineParts.machineparts'),
        ),
    ]
