# Generated by Django 4.2.5 on 2023-09-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachineParts', '0003_ratingmachineparts_machine_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMachineParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'machine_parts_category',
            },
        ),
        migrations.AlterField(
            model_name='machineparts',
            name='tags',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='ConcreteCategoryMachineParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineParts.categorymachineparts')),
                ('machine_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MachineParts.machineparts')),
            ],
            options={
                'db_table': 'machine_parts_category_concrete',
            },
        ),
    ]
