# Generated by Django 4.2.5 on 2023-10-05 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'machine_part_category',
            },
        ),
        migrations.CreateModel(
            name='MachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_no', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.FloatField()),
                ('tags', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('made_in', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_parts.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.mechanic')),
            ],
            options={
                'db_table': 'machine_part',
            },
        ),
    ]
