# Generated by Django 4.2.5 on 2023-09-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
