# Generated by Django 4.2.5 on 2023-09-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='shared_user',
        ),
    ]
